### ISSUE TITLE
Plugin not working 

### ISSUE THREAD

**Issue by ezeaniiandrew** [bajrangCoder/acode-react-snippets#10]
I've tried using the plugin but it doesn't seem to work. Typing the snippet doesn't bring up any suggestions. Are there extra configuration I have to set before it starts to work? 

https://github.com/bajrangCoder/acode-react-snippets/assets/98923593/cadc8f6b-7840-4bdd-9a50-f5298b67b74b

Acode version: 1.8.7

**Comment by bajrangCoder** [comment]
Change the mode to jsx from pencil(✏️) icon

**Comment by ezeaniiandrew** [comment]
The original file is a jsx file, but I still renamed it using the ✏️ icon as you suggested but it's still not working.

**Comment by bajrangCoder** [comment]
I mean check the mode your file, is it set to jsx or tsx?

Because this plugin only adds snippet in jsx and tsx mode

**Comment by ezeaniiandrew** [comment]
How do I check my file mode?

**Comment by bajrangCoder** [comment]
From `✏️ > Syntax Highlighting `

**Comment by ezeaniiandrew** [comment]
Thanks it worked. Will there be a future update to support `.js` files?

**Comment by bajrangCoder** [comment]
That's intentionally not added for `.js`

Because there are a lot of snippets and completions already available for javascript mode and if I will add this to them it might be start lagging

Btw it's not hard to add `.js` or `.ts` etc it can be added with a single line

**Comment by ezeaniiandrew** [comment]
Alright. I'm just asking because I've added some vanilla JavaScript snippets to the plugin. But since I'm not familiar with the ace editor, I don't know how to configure it to pick up those snippets. I'll create a pull request once I'm done so you can review it.

**Comment by bajrangCoder** [comment]
Yes, you can add those snippets but make sure to add `javascript` in file type option then only it will work in javascript mode and also its not hard to create snippet, you just have to add your prefix, snippet, etc in `snippets.ts` of this plugin

https://github.com/bajrangCoder/acode-react-snippets/blob/8218c71c6efd2c5b6e71b7eb308098a36732461b/src/snippets.ts#L19

**Comment by ezeaniiandrew** [comment]
Alright, thanks for the help.
