### ISSUE TITLE
I can't find this plugin

### ISSUE THREAD

**Issue by ezeaniiandrew** [bajrangCoder/acode-react-snippets#6]
I'm using Acode v1.8.7 and I can't find the plugin in the extensions. The snippets plugin created by Ajit Kumar is the only available one.

**Comment by bajrangCoder** [comment]
This plugin isn't published yet!(Basically because I'm busy due to religious event(Pooja))
You can test it by clonning the repo and building it.

**Comment by ezeaniiandrew** [comment]
Oh! Alright. Thought it was a problem with my version of Acode.
 Is the plugin strictly for ES7/React/Redux snippets? I'm considering contributing to the project by adding javascript snippets other than ES7 to the plugin.

**Comment by bajrangCoder** [comment]
No just given the name 😁
Yes you can contribute and just you will need to modify `src/snippets.ts` snippet array

> btw this plugin is for react/nextjs etc(not strictly)

**Comment by bajrangCoder** [comment]
This plugin is now available on store

https://acode.app/plugin/bajrangcoder.react.snippets

**Comment by ezeaniiandrew** [comment]
Nice! I'll check it out
