### ISSUE TITLE
Approch! 🙏 Create A Ziglang mode for ace (Acode)

### ISSUE THREAD

**Issue by shaikhahemad** [bajrangCoder/acode-react-snippets#9]
Create Syntax Highlighter and snippets for Zig  programming language.

**Comment by bajrangCoder** [comment]
for me creating a mode is really hard but i will try

**Comment by bajrangCoder** [comment]
for me creating a mode is really hard but i will try

**Comment by bajrangCoder** [comment]
for me creating a mode is really hard but i will try

**Comment by bajrangCoder** [comment]
https://github.com/ajaxorg/ace/pull/5429
